### ISSUE TITLE
Milestone 1 Feedback

### ISSUE THREAD

**Issue by ashkon91** [easonychang/cogs121#2]
Hey hey team cs cube

I feel like Spotify Mood fits the course description the best out of the proposed ideas. However I would suggest thinking past just the idea of mood and see what other information you could figure out about the user given their listening history. I think that there are a lot of interesting things you can see in a person based on their listening habits. You should also take a look at the [LastFM APIs](https://www.last.fm/api) as they are also another big music tracking service! 

If you have any followup questions you can reply to this issue with (@ashkon91) or make a private piazza post and I'll be more than glad to help you all out!

Best,
Ashkon

**Comment by easonychang** [comment]
Thank for the feedback Ashkon!
